apiVersion: autoscaling/v2

kind: HorizontalPodAutoscaler

metadata:
  name: api-hpa
  namespace: k8-nagp-demo-ns

spec:

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: productapi

  minReplicas: 4
  maxReplicas: 10

  metrics:
  - type: Resource

    resource:
      name: cpu

      target:
        type: Utilization
        averageUtilization: 70