apiVersion: v1
kind: Service

metadata:
  name: product-api-service
  namespace: k8-nagp-demo-ns

spec:
  selector:
    app: product-api-app

  ports:
  - port: 80
    targetPort: 8080

  type: ClusterIP